[build]
  # Skip the build command - just deploy files as-is
  command = "echo 'No build needed'"
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"